site_name: Sibyl
theme: readthedocs
docs_dir: sources
site_url: http://pyrite.startup.ml
site_description: Anomaly Detection in High Dimensional Heterogeneous Datasets
site_favicon: favicon.ico
copyright: © 2014-2016 Startup.ML, LLC. All rights reserved.
dev_addr: '0.0.0.0:8000'
extra_css: [extra.css]
google_analytics: ['UA-70335803-1', 'pyrite.startup.ml']

pages:
- Home: index.md
- API: documentation.md
- Examples: examples.md
- FAQ: faq.md
- License: license.md
