site_name: Sibyl Documentation
theme: readthedocs
docs_dir: sources
repo_url: https://github.com/startupml/sibyl
site_url: http://startupml.github.io/sibyl
site_description: Anomaly Detection in High Dimensional Heterogeneous Datasets

dev_addr: '0.0.0.0:8000'
google_analytics: ['', '']

pages:
- Home: index.md
- Index: documentation.md
- Examples: examples.md
- FAQ: faq.md
